"""ReplayEngine — deterministic replay of recorded events through a kernel.

The same event stream that was recorded live (or generated by a simulator)
drives the same TradingKernel with a ReplayClock. Strategies make identical
decisions to live trading — the zero-parity invariant.
"""

from __future__ import annotations

from ntrade.kernel.clock import ReplayClock
from ntrade.kernel.session import TradingKernel


class ReplayEngine:
    def __init__(self, kernel: TradingKernel | None = None, *, clock: ReplayClock | None = None,
                 timeframe: str = "1m", **kw):
        self.clock = clock or ReplayClock()
        self.kernel = kernel or TradingKernel(mode="replay", clock=self.clock,
                                              timeframe=timeframe, **kw)

    def run(self, events, *, start=None) -> TradingKernel:
        """Replay an event iterable through the kernel; returns the kernel."""
        return self.kernel.run_replay(events, start=start)
