"""Market-data service — the single seam between the UI backend and nTrade.

Design goals (per docs/superpowers/specs/2026-08-02-trading-ui-design.md):
  * The UI must never depend on a particular broker API. Every REST route and
    the live candle pump talk to :class:`MarketDataService`, which delegates
    candle/quote reads to a :class:`CandleProvider`.
  * Instrument metadata (roots, futures contracts, expiries) is real Dhan
    instrument-master data (the daily ``all_instrument*.csv`` dumps that
    already ship in this repo) parsed by :class:`FuturesMaster`.
  * Candles are normalized to the frontend candle DTO::

        {"time": int_utc_epoch_seconds, "open": f, "high": f,
         "low": f, "close": f, "volume": int}

Providers
  * ``DhanProvider``    — live broker (needs ``.env`` Dhan credentials).
  * ``ParquetProvider`` — offline ``ParquetStorage`` reads.
  * ``SyntheticProvider`` — deterministic seeded OHLCV for local dev / replay
    demos / tests (uses the same session-grid + walk family as the sim layer).
"""

from __future__ import annotations

import csv
import hashlib
import json
import logging
import os
import random
import re
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path
from typing import Protocol
from zoneinfo import ZoneInfo

log = logging.getLogger("api.marketdata")

# Roots the futures terminal exposes (the UI's root selector shows only these).
# The master still parses the full Dhan dump; this is the display boundary.
SUPPORTED_ROOTS = ("NIFTY", "BANKNIFTY",
                   "CRUDEOIL", "CRUDEOILM", "GOLD", "GOLDM", "SILVER", "SILVERM")

from ntrade.domain.constants import Exchange, Timeframe
from ntrade.domain.market_hours import DAILY_TIMEFRAMES, session_close

# IST market session: 09:15–15:30. Bars are generated on this grid and then
# converted to UTC epoch seconds for the wire.
_SESSION_TZ = ZoneInfo("Asia/Kolkata")
_SESSION_OPEN = time(9, 15)
_SESSION_CLOSE = time(15, 30)
_SESSION_MINUTES = 375  # 09:15 → 15:30

# UI interval -> session bar span in minutes (1D = one bar per session day).
# Keyed by the exact wire strings the REST layer accepts (not the Timeframe
# enum values, which are lowercase and would miss "1D").
_INTERVAL_MINUTES = {"1m": 1, "5m": 5, "15m": 15, "1h": 60, "1D": 375}
VALID_INTERVALS = tuple(_INTERVAL_MINUTES)

# Deterministic "base" anchor prices for well-known roots (synthetic provider);
# unknown roots get a hash-derived anchor in the same band.
_KNOWN_BASE = {"NIFTY": 24800.0, "BANKNIFTY": 55500.0, "FINNIFTY": 23200.0,
               "MIDCPNIFTY": 12600.0, "SENSEX": 81500.0}

# 90 calendar days of 1m MCX (09:00–23:30) is ~78k bars if every day traded.
MAX_CANDLES_LIMIT = 100_000
def _base_price(root: str) -> float:
    """Deterministic synthetic anchor price for ``root`` (a known index root
    or any symbol). Canonical formula shared by every synthetic source so the
    same symbol anchors identically regardless of code path."""
    if root in _KNOWN_BASE:
        return _KNOWN_BASE[root]
    digest = int.from_bytes(hashlib.md5(root.encode()).digest()[:8], "big")
    return round(15_000.0 + (digest % 55_000) / 10.0, 2)


DEFAULT_DAYS = 8  # synthetic sessions generated by default
LIVE_HISTORY_DAYS = 90  # raw DhanProvider with no dates (backfill / tests)
CHART_DAYS = 3  # UI + MarketDataService default window (weekdays, IST)
# Cap on how far back SyntheticProvider will lazily extend its session grid
# when a request asks for a wider window. Mirrors the Dhan provider's
# 90-calendar-day history horizon; requests older than this return empty
# (the same no-data contract as the real providers).
MAX_SYNTH_SESSIONS = 90
# Ceiling on synthesized replay ticks per request. Ticks ride the compact
# per-bar wire format (prices/quantities arrays), so a full 1m contract
# history (~19k bars x 60 ticks) is only ~10MB of JSON — well under this.
MAX_TICKS = 1_500_000


class MarketDataError(RuntimeError):
    """Raised when a provider cannot serve the request (surfaced as 503)."""


# --------------------------------------------------------------------------- DTOs


@dataclass(frozen=True)
class Candle:
    """Normalized candle DTO — ``time`` is UTC epoch seconds."""

    time: int
    open: float
    high: float
    low: float
    close: float
    volume: int

    def as_dict(self) -> dict:
        return {"time": self.time, "open": self.open, "high": self.high,
                "low": self.low, "close": self.close, "volume": self.volume}


def candle_from_row(row: dict) -> Candle | None:
    """Build a Candle from a normalized OHLCV row dict (lowercase keys)."""
    try:
        ts = row["timestamp"]
        if isinstance(ts, datetime):
            dt = ts
        else:
            dt = datetime.fromisoformat(str(ts))
    except (KeyError, TypeError, ValueError):
        return None
    if dt.tzinfo is None:
        # Domain convention: naive timestamps are IST wall time (parquet store
        # strips tz; Dhan ships tz-aware). Interpret naive as IST before
        # converting to UTC epoch so the wire time is unambiguous.
        dt = dt.replace(tzinfo=_SESSION_TZ)
    else:
        dt = dt.astimezone(timezone.utc)
    return Candle(
        time=int(dt.timestamp()),
        open=float(row.get("open") or 0.0),
        high=float(row.get("high") or 0.0),
        low=float(row.get("low") or 0.0),
        close=float(row.get("close") or 0.0),
        volume=int(row.get("volume") or 0),
    )


def normalize_candles(rows: list[dict] | list[Candle], *, limit: int | None = None) -> list[dict]:
    """Sort + dedupe (by time) + clamp a raw candle list to the wire shape."""
    candles: list[Candle] = []
    seen: set[int] = set()
    for row in rows:
        c = row if isinstance(row, Candle) else candle_from_row(row)
        if c is None or c.time in seen:
            continue
        seen.add(c.time)
        candles.append(c)
    candles.sort(key=lambda c: c.time)
    if limit is not None and len(candles) > limit:
        candles = candles[-limit:]
    return [c.as_dict() for c in candles]


# ------------------------------------------------------------------ instrument master


@dataclass(frozen=True)
class Contract:
    """A futures contract as advertised by the instrument master."""

    contract_id: str          # Dhan trading symbol, e.g. "NIFTY-Oct2026-FUT"
    symbol: str               # Dhan custom symbol, e.g. "NIFTY OCT FUT"
    root: str
    exchange: str
    expiry: date
    lot_size: float
    tick_size: float
    security_id: int | None
    instrument_name: str = ""  # FUTIDX (index) / FUTSTK (stock) / FUTCOM ...

    def as_dict(self, *, today: date | None = None, is_front_month: bool = False) -> dict:
        today = today or date.today()
        dte = (self.expiry - today).days
        return {
            "contract_id": self.contract_id,
            "symbol": self.symbol,
            "root": self.root,
            "exchange": self.exchange,
            "expiry": self.expiry.isoformat(),
            "days_to_expiry": dte,
            "is_expired": dte < 0,
            "is_front_month": is_front_month,
            "lot_size": self.lot_size,
            "tick_size": self.tick_size,
            "security_id": self.security_id,
        }

    @property
    def is_index(self) -> bool:
        return self.instrument_name == "FUTIDX"


def _glob_instrument_csvs() -> list[Path]:
    """Locate Dhan instrument dumps (repo root + Dependencies/, newest first).

    The downloads historically land as ``Dependencies\\all_instrument
    YYYY-MM-DD.csv`` (Windows-style backslash in the *filename*, at the repo
    root) — glob with a tolerant pattern that also covers a real
    ``Dependencies/`` directory.
    """
    root = Path(__file__).resolve().parent.parent
    candidates: list[Path] = []
    for pattern in ("*all_instrument*.csv", "*all_instrument*"):
        candidates.extend(p for p in root.glob(pattern) if p.is_file())
    deps_dir = root / "Dependencies"
    if deps_dir.is_dir():
        candidates.extend(p for p in deps_dir.glob("*all_instrument*.csv") if p.is_file())
    # De-duplicate by resolved path and keep newest-modified first.
    # Skip empty dumps (Tradehull sometimes creates a 0-byte file before
    # the download finishes / when the fetch fails).
    seen: set[str] = set()
    out: list[Path] = []
    for p in sorted(candidates, key=lambda p: p.stat().st_mtime, reverse=True):
        if p.stat().st_size <= 0:
            continue
        key = str(p.resolve())
        if key not in seen:
            seen.add(key)
            out.append(p)
    return out


class FuturesMaster:
    """Parsed Dhan instrument master — futures contracts by root symbol."""

    def __init__(self, csv_path: str | Path | None = None):
        self.source_path: Path | None = None
        self._contracts: dict[str, list[Contract]] = {}
        candidates = [Path(csv_path)] if csv_path is not None else _glob_instrument_csvs()
        for path in candidates:
            if not path.exists() or path.stat().st_size <= 0:
                continue
            try:
                self._load(path)
                return
            except Exception:
                # Corrupt/truncated dump — try the next newest file.
                self.source_path = None
                self._contracts = {}
                continue

    # ------------------------------------------------------------------ load
    def _load(self, path: Path) -> None:
        self.source_path = path
        by_root: dict[str, list[Contract]] = {}
        seen_ids: set[str] = set()
        with open(path, newline="", encoding="utf-8-sig") as fh:
            reader = csv.reader(fh)
            header = next((r for r in reader if r and r[1] == "SEM_EXM_EXCH_ID"), None)
            if header is None:
                raise MarketDataError(f"instrument master has no header: {path}")
            idx = {name: i for i, name in enumerate(header)}
            exch_col = idx.get("SEM_EXM_EXCH_ID")
            for row in reader:
                if len(row) < len(header):
                    continue
                inst_type = row[idx["SEM_EXCH_INSTRUMENT_TYPE"]].strip().upper()
                # Index/stock F&O dumps use FUT; MCX commodity futures use FUTCOM.
                if inst_type not in ("FUT", "FUTCOM"):
                    continue
                custom = row[idx["SEM_CUSTOM_SYMBOL"]].strip().upper()
                trading = row[idx["SEM_TRADING_SYMBOL"]].strip()
                if not custom or not trading or " " not in custom:
                    continue
                root = custom.split(" ", 1)[0]
                try:
                    expiry = datetime.strptime(
                        row[idx["SEM_EXPIRY_DATE"]].strip(), "%Y-%m-%d %H:%M:%S"
                    ).date()
                except ValueError:
                    continue
                contract_id = trading
                if contract_id in seen_ids:
                    continue
                seen_ids.add(contract_id)
                exch_id = row[exch_col].strip().upper() if exch_col is not None else ""
                exchange = Exchange.MCX if exch_id == "MCX" else Exchange.DERIVATIVES
                by_root.setdefault(root, []).append(Contract(
                    contract_id=contract_id,
                    symbol=custom,
                    root=root,
                    exchange=exchange,
                    expiry=expiry,
                    lot_size=_f(row[idx["SEM_LOT_UNITS"]]),
                    tick_size=_f(row[idx["SEM_TICK_SIZE"]]),
                    security_id=_int_or_none(row[idx["SEM_SMST_SECURITY_ID"]]),
                    instrument_name=row[idx["SEM_INSTRUMENT_NAME"]].strip().upper(),
                ))
        # Keep only roots with a futures contract set, sorted by expiry
        self._contracts = {root: sorted(lst, key=lambda c: c.expiry)
                           for root, lst in by_root.items()}

    # ------------------------------------------------------------------ query
    @property
    def loaded(self) -> bool:
        return self.source_path is not None

    def roots(self) -> list[str]:
        """All root symbols, index futures (FUTIDX) first."""
        idx = sorted(r for r, lst in self._contracts.items()
                     if any(c.is_index for c in lst))
        others = sorted(r for r in self._contracts if r not in idx)
        return idx + others

    def futures_roots(self) -> list[str]:
        """Roots with any tradeable futures contract (index, stock, commodity)."""
        return sorted(self._contracts)

    def index_roots(self) -> list[str]:
        """Root symbols with index futures only (NIFTY, BANKNIFTY, ...)."""
        return sorted(r for r, lst in self._contracts.items()
                      if any(c.is_index for c in lst))

    def contracts(self, root: str) -> list[Contract]:
        return self._contracts.get(root.upper(), [])

    def resolve(self, symbol: str) -> Contract | None:
        """Resolve a UI symbol (custom/trading/``root EXPIRY`` form) to a contract."""
        symbol = symbol.strip().upper()
        for lst in self._contracts.values():
            for c in lst:
                if c.symbol == symbol or c.contract_id == symbol:
                    return c
        # "NIFTY 2026-10-27" / "NIFTY 27Oct26" style lookups
        parts = symbol.split()
        if len(parts) >= 2:
            root = parts[0]
            for c in self._contracts.get(root, []):
                if symbol in (f"{root} {c.expiry.isoformat()}", f"{root} {c.expiry:%d%b%y}"):
                    return c
        return None

    def front_month(self, root: str) -> Contract | None:
        """Nearest not-yet-expired contract (fall back to nearest overall)."""
        lst = self._contracts.get(root.upper(), [])
        if not lst:
            return None
        today = date.today()
        active = [c for c in lst if c.expiry >= today]
        return (active[0] if active else lst[0])


# --------------------------------------------------------------------- providers


class CandleProvider(Protocol):
    """Candle/quote backend. ``name`` is reported to the UI (``source``)."""

    name: str

    def candles(self, *, symbol: str, exchange: str, interval: str,
                start: datetime | None = None, end: datetime | None = None,
                limit: int | None = None) -> list[dict]:
        ...

    def quote(self, *, symbol: str, exchange: str) -> dict:
        ...


class DhanProvider:
    """Real broker candles/quotes through the existing DhanBroker adapter."""

    name = "dhan"

    def __init__(self, master: FuturesMaster, env_path: str = ".env",
                 env: dict | None = None, data_dir: str | None = None):
        self._master = master
        self._env_path = env_path
        self._env = env
        # Parquet datalake root — the same store ParquetProvider reads, so
        # every fetched futures history is available offline.
        self._data_dir = data_dir or os.environ.get("NTRADE_DATA_DIR", "data/ohlcv")
        self._broker = None
        self._factory = None
        self._last_error: str | None = None

    # ------------------------------------------------------------------ auth
    @property
    def connected(self) -> bool:
        return self._broker is not None

    def _ensure(self) -> None:
        if self._broker is not None:
            return
        from ntrade.brokers.dhan import DhanBroker
        from ntrade.factories import InstrumentFactory
        try:
            broker = DhanBroker(env_path=self._env_path, env=self._env, connect=True)
            self._broker = broker
            self._factory = InstrumentFactory(broker=broker)
        except Exception as exc:  # auth/TOTP/network failures surface cleanly
            self._last_error = str(exc)
            raise MarketDataError(
                f"Dhan broker unavailable ({exc}); check .env credentials"
            ) from exc

    def feed_auth(self) -> tuple[str, str]:
        """Client-id + token for dhanhq MarketFeed (live UI ticks)."""
        self._ensure()
        tsl = self._broker.tsl
        return str(tsl.ClientCode), str(tsl.token_id)

    def _instrument(self, symbol: str) -> object:
        """Build the domain instrument for a symbol (Future when resolvable)."""
        contract = self._master.resolve(symbol)
        root = (contract.root if contract else symbol.split()[0]).upper()
        if contract is not None and contract.exchange == Exchange.MCX:
            underlying = self._factory.commodity(root)
        else:
            underlying = self._factory.index(root)
        if contract is None:
            return underlying
        return self._factory.future(underlying, contract.expiry)

    # ------------------------------------------------------------------ data
    def candles(self, *, symbol: str, exchange: str, interval: str,
                start: datetime | None = None, end: datetime | None = None,
                limit: int | None = None) -> list[dict]:
        self._ensure()
        # No dates → 90 calendar days through today (backfill / direct calls).
        # Chart/UI goes through MarketDataService, which fills a 3-weekday window.
        # get_historical_data ignores dates (post-filter only) and often stops
        # at the last completed session — use the dated endpoint.
        if end is None:
            end = datetime.now(tz=_SESSION_TZ)
        if start is None:
            start = end - timedelta(days=LIVE_HISTORY_DAYS)
        try:
            inst = self._instrument(symbol)
            series = self._broker.get_long_term_historical(
                inst, timeframe=interval, from_date=start, to_date=end,
            )
            df = series.to_dataframe() if hasattr(series, "to_dataframe") else series
        except Exception as exc:
            raise MarketDataError(f"Dhan history fetch failed: {exc}") from exc
        if df is None or df.empty:
            return []
        df = df.copy()
        df.columns = [str(c).lower() for c in df.columns]
        rows = normalize_candles(df.to_dict("records"))
        # Clamp before write-through so the parquet lake never stores the
        # post-close ghost bars either (offline reads then stay clean too).
        rows = _clamp_to_session(rows, exchange=exchange, interval=interval)
        if limit is not None and len(rows) > limit:
            rows = rows[-limit:]
        self._write_through(symbol=symbol, exchange=exchange, interval=interval,
                            kind=getattr(inst, "KIND", "future"), rows=rows)
        return rows

    def _write_through(self, *, symbol: str, exchange: str, interval: str,
                       kind: str, rows: list[dict]) -> None:
        """Persist fetched candles into the Parquet datalake (best-effort).

        Writes only supported futures roots (index + MCX commodity) into the
        same store :class:`ParquetProvider` reads, so broker history becomes
        available offline. Timestamps are stored as naive IST wall time — the
        parquet store's contract — and round-trip exactly to the wire's UTC
        epochs via :func:`candle_from_row`. A storage failure must never fail
        the request, so every failure is swallowed (logged).
        """
        if not rows:
            return
        contract = self._master.resolve(symbol)
        root = (contract.root if contract else symbol.split()[0]).upper()
        if contract is None or root not in SUPPORTED_ROOTS:
            return
        try:
            from ntrade.data.parquet_store import ParquetStorage

            ParquetStorage(self._data_dir).upsert(parquet_frame(
                symbol=symbol, exchange=exchange, interval=interval,
                kind=kind, rows=rows))
        except Exception as exc:  # cache write must never break the request
            log.warning("parquet write-through failed for %s: %s", symbol, exc)

    def quote(self, *, symbol: str, exchange: str) -> dict:
        self._ensure()
        try:
            inst = self._instrument(symbol)
            q = self._broker.get_quote(inst)
        except Exception as exc:
            raise MarketDataError(f"Dhan quote fetch failed: {exc}") from exc
        prev_close = float(q.prev_close or 0.0)
        ltp = float(q.ltp or 0.0)
        high = float(q.high or 0.0)
        low = float(q.low or 0.0)
        open_ = float(q.open or 0.0)
        volume = int(q.volume or 0)
        # Dhan's quote-data enrichment can fail silently (the transport
        # swallows the error), leaving OHLC/prev_close at zero while LTP and
        # volume still come through. Fall back to the provider's own daily
        # series so the terminal header never shows an all-zero OHLC or a
        # bogus +100% change.
        if not (high and low and open_ and prev_close):
            rows = self.candles(symbol=symbol, exchange=exchange,
                                interval=Timeframe.D1, limit=2)
            if rows:
                last = rows[-1]
                prev = rows[-2] if len(rows) > 1 else rows[-1]
                high = high or float(last["high"])
                low = low or float(last["low"])
                open_ = open_ or float(last["open"])
                prev_close = prev_close or float(prev["close"])
                volume = volume or int(last.get("volume") or 0)
        change = ltp - prev_close
        return {
            "symbol": symbol,
            "exchange": exchange,
            "ltp": round(ltp, 2),
            "change": round(change, 2),
            "change_pct": round((change / prev_close * 100.0) if prev_close else 0.0, 2),
            "high": round(high, 2),
            "low": round(low, 2),
            "open": round(open_, 2),
            "prev_close": round(prev_close, 2),
            "volume": volume,
            "oi": int(q.oi or 0),
            "source": self.name,
        }


def parquet_frame(*, symbol: str, exchange: str, interval: str,
                  kind: str, rows: list[dict]) -> "pd.DataFrame":
    """Rows -> the parquet store's DataFrame shape (naive IST timestamps)."""
    import pandas as pd
    ist = [datetime.fromtimestamp(r["time"], tz=_SESSION_TZ).replace(tzinfo=None)
           for r in rows]
    return pd.DataFrame({
        "symbol": [symbol] * len(rows),
        "exchange": [exchange] * len(rows),
        "kind": [kind] * len(rows),
        "timeframe": [interval.lower()] * len(rows),
        "timestamp": ist,
        "open": [r["open"] for r in rows],
        "high": [r["high"] for r in rows],
        "low": [r["low"] for r in rows],
        "close": [r["close"] for r in rows],
        "volume": [r["volume"] for r in rows],
    })


class ParquetProvider:
    """Offline candles from the existing ParquetStorage store."""

    name = "parquet"

    def __init__(self, master: FuturesMaster, base_path: str | Path = "data/ohlcv"):
        self._master = master
        self._base_path = str(base_path)

    def candles(self, *, symbol: str, exchange: str, interval: str,
                start: datetime | None = None, end: datetime | None = None,
                limit: int | None = None) -> list[dict]:
        from ntrade.data.parquet_store import ParquetStorage
        store = ParquetStorage(self._base_path)
        tf = interval.lower()
        df = store.read(symbols=[symbol], start=start, end=end, timeframe=tf)
        if df.empty:
            return []
        return normalize_candles(df.to_dict("records"), limit=limit)

    def quote(self, *, symbol: str, exchange: str) -> dict:
        rows = self.candles(symbol=symbol, exchange=exchange, interval=Timeframe.D1, limit=1)
        if not rows:
            # Offline stores often lack D1 (the dhan write-through persists the
            # requested timeframe, typically 1m) — aggregate daily bars from the
            # stored intraday data so the header quote never fails offline.
            intraday = self.candles(symbol=symbol, exchange=exchange, interval="1m")
            rows = _aggregate_daily(intraday)
        if not rows:
            raise MarketDataError(f"no stored data for {symbol}")
        last = rows[-1]
        prev_rows = rows[:-1]  # already sorted ascending — previous session is rows[-2]
        prev_close = float(prev_rows[-1]["close"]) if prev_rows else last["close"]
        ltp = float(last["close"])
        change = ltp - prev_close
        return {
            "symbol": symbol,
            "exchange": exchange,
            "ltp": round(ltp, 2),
            "change": round(change, 2),
            "change_pct": round((change / prev_close * 100.0) if prev_close else 0.0, 2),
            "high": float(last["high"]),
            "low": float(last["low"]),
            "open": float(last["open"]),
            "prev_close": prev_close,
            "volume": int(last.get("volume") or 0),
            "oi": 0,
            "source": self.name,
        }


def _clamp_to_session(rows: list[dict], *, exchange: str,
                      interval: str) -> list[dict]:
    """Drop intraday bars whose IST start time is at/past the exchange's
    session close. Dhan ships bars that start after the close (1m to 15:39,
    5m to 15:35 on NSE) while the live pump stops exactly at the close — those
    ghost bars break the chart's right-edge seam. Daily bars anchor at
    midnight (before the open), so the clamp applies to intraday only."""
    if interval.lower() in DAILY_TIMEFRAMES:
        return rows
    cl = session_close(exchange)
    return [c for c in rows
            if datetime.fromtimestamp(c["time"], tz=_SESSION_TZ).time() < cl]


def _aggregate_daily(rows: list[dict]) -> list[dict]:
    """Aggregate intraday wire candles into per-IST-day bars (ascending)."""
    by_day: dict[date, dict] = {}
    for r in rows:
        day = datetime.fromtimestamp(r["time"], tz=_SESSION_TZ).date()
        d = by_day.get(day)
        if d is None:
            midnight = datetime.combine(day, time.min, tzinfo=_SESSION_TZ)
            by_day[day] = {"time": int(midnight.timestamp()), "open": r["open"],
                           "high": r["high"], "low": r["low"],
                           "close": r["close"], "volume": r["volume"]}
        else:
            d["high"] = max(d["high"], r["high"])
            d["low"] = min(d["low"], r["low"])
            d["close"] = r["close"]
            d["volume"] = d["volume"] + r["volume"]
    return [by_day[d] for d in sorted(by_day)]


class SyntheticProvider:
    """Deterministic seeded OHLCV generator for offline dev / replay / tests.

    Uses the same family of ideas as ``ntrade.sim.tick_simulator``: a seeded
    mean-reverting random walk over the IST session grid (09:15–15:30,
    weekdays only). Identical inputs produce identical candles, so replay
    behaviour and tests are stable. Clearly labelled ``source: "synthetic"``.
    """

    name = "synthetic"

    def __init__(self, master: FuturesMaster, days: int = DEFAULT_DAYS, seed: int = 7):
        self._master = master
        self._days = days
        self._seed = seed
        # Keyed by generation date so a server running across midnight anchors
        # to the new "last N sessions" instead of serving stale history forever.
        self._cache: dict[tuple[str, str, date], list[Candle]] = {}

    # ------------------------------------------------------------------ gen
    def _rng(self, symbol: str, interval: str) -> random.Random:
        key = f"{symbol}|{interval}|{self._seed}".encode()
        digest = int.from_bytes(hashlib.md5(key).digest()[:8], "big")
        return random.Random(digest)

    def _base_price(self, root: str) -> float:
        return _base_price(root)

    def _session_days(self, floor: date | None = None) -> list[date]:
        """Weekday sessions covering at least ``self._days`` sessions, extended
        backward to include ``floor`` when a chart window wider than the
        default requests it (a wide request must not be silently truncated)."""
        need = max(self._days, 1)
        if floor is not None:
            # Lazy extension is bounded by the history horizon so ancient
            # ranges keep the real providers' "no data" contract — but a
            # configured `self._days` above the cap is never truncated.
            need = max(need, min((date.today() - floor).days * 5 // 7 + 2,
                                 MAX_SYNTH_SESSIONS))
        days: list[date] = []
        d = date.today()
        while len(days) < need:
            if d.weekday() < 5:  # Mon–Fri
                days.append(d)
            d -= timedelta(days=1)
        return days[::-1]

    def _series(self, symbol: str, interval: str,
                floor: date | None = None) -> list[Candle]:
        key = (symbol, interval, floor or date.today())
        if key in self._cache:
            return self._cache[key]
        root = symbol.split()[0].upper()
        base = self._base_price(root)
        rng = self._rng(symbol, interval)
        span = _INTERVAL_MINUTES[interval]
        bar_span = timedelta(minutes=span) if span < 375 else timedelta(minutes=375)
        out: list[Candle] = []
        price = base
        for day in self._session_days(floor):
            # Daily bars anchor at midnight IST, matching Dhan's daily history
            # and the live pump's 1D grid — intraday bars stay on the
            # session-open grid.
            t0 = (datetime.combine(day, time.min, tzinfo=_SESSION_TZ)
                  if span >= _SESSION_MINUTES
                  else datetime.combine(day, _SESSION_OPEN, tzinfo=_SESSION_TZ))
            n_bars = _SESSION_MINUTES // span
            for k in range(n_bars):
                ret = rng.uniform(-0.0035, 0.0035) * (span ** 0.5) + rng.uniform(-0.0002, 0.0002)
                close = max(price * (1.0 + ret), 0.01)
                gap = 1.0 + rng.uniform(-0.0004, 0.0004) if k else 1.0
                open_ = price * gap
                high = max(open_, close) * (1.0 + rng.uniform(0.0, 0.0018))
                low = min(open_, close) * (1.0 - rng.uniform(0.0, 0.0018))
                lot = self._contract_lot(symbol) or 25.0
                volume = int(lot * (30 + rng.uniform(0.0, 220.0)))
                out.append(Candle(
                    time=int((t0 + k * bar_span).timestamp()),
                    open=round(open_, 2), high=round(high, 2),
                    low=round(low, 2), close=round(close, 2),
                    volume=volume,
                ))
                price = close
        self._cache[key] = out
        return out

    def _contract_lot(self, symbol: str) -> float | None:
        contract = self._master.resolve(symbol)
        return contract.lot_size if contract and contract.lot_size else None

    # ------------------------------------------------------------------ data
    def candles(self, *, symbol: str, exchange: str, interval: str,
                start: datetime | None = None, end: datetime | None = None,
                limit: int | None = None) -> list[dict]:
        floor = start.date() if start is not None else None
        series = self._series(symbol, interval, floor)
        if start is not None or end is not None:
            start_ts = start.timestamp() if start else None
            end_ts = end.timestamp() if end else None
            series = [c for c in series
                      if (start_ts is None or c.time >= start_ts)
                      and (end_ts is None or c.time <= end_ts)]
        if not series:
            return []
        if limit is not None and len(series) > limit:
            series = series[-limit:]
        return [c.as_dict() for c in series]

    def quote(self, *, symbol: str, exchange: str) -> dict:
        rows = self.candles(symbol=symbol, exchange=exchange, interval=Timeframe.MIN, limit=1)
        if not rows:
            raise MarketDataError(f"no data for {symbol}")
        last = rows[-1]
        prev_rows = self.candles(symbol=symbol, exchange=exchange, interval=Timeframe.MIN, limit=2)
        prev_close = float(prev_rows[-2]["close"]) if len(prev_rows) > 1 else last["close"]
        ltp = float(last["close"])
        change = ltp - prev_close
        return {
            "symbol": symbol,
            "exchange": exchange,
            "ltp": round(ltp, 2),
            "change": round(change, 2),
            "change_pct": round((change / prev_close * 100.0) if prev_close else 0.0, 2),
            "high": float(last["high"]),
            "low": float(last["low"]),
            "open": float(last["open"]),
            "prev_close": prev_close,
            "volume": int(last.get("volume") or 0),
            "oi": 0,
            "source": self.name,
        }


# ---------------------------------------------------------------------- service


class MarketDataService:
    """Composition root: instrument master + one candle/quote provider."""

    def __init__(self, provider: CandleProvider, master: FuturesMaster | None = None):
        self.provider = provider
        self.master = master or FuturesMaster()

    @property
    def name(self) -> str:
        return self.provider.name

    # ------------------------------------------------------------------ meta
    def describe(self) -> dict:
        return {
            "provider": self.name,
            "instrument_master_loaded": self.master.loaded,
            "instrument_master_source": str(self.master.source_path)
            if self.master.source_path else None,
            "live": self.name == "dhan",
            "roots": self.roots(),
        }

    def roots(self) -> list[dict]:
        today = date.today()
        out = []
        # master.roots() puts index futures first, then commodity/other.
        for root in self.master.roots():
            if root not in SUPPORTED_ROOTS:
                continue  # terminal's curated universe only
            contracts = self.master.contracts(root)
            front = self.master.front_month(root)
            out.append({
                "root": root,
                "exchange": front.exchange if front else Exchange.DERIVATIVES,
                "display_name": f"{root} Futures",
                "n_contracts": len(contracts),
                "front_month": front.as_dict(today=today) if front else None,
            })
        return out

    def contracts(self, root: str) -> list[dict]:
        today = date.today()
        front = self.master.front_month(root)
        front_id = front.contract_id if front else None
        return [c.as_dict(today=today, is_front_month=c.contract_id == front_id)
                for c in self.master.contracts(root)]

    def has_root(self, root: str) -> bool:
        return bool(self.master.contracts(root))

    # ------------------------------------------------------------------ data
    def candles(self, *, symbol: str, exchange: str = Exchange.DERIVATIVES,
                interval: str = Timeframe.MIN, start: datetime | None = None,
                end: datetime | None = None, limit: int | None = None) -> list[dict]:
        if end is None:
            end = datetime.now(tz=_SESSION_TZ)
        if start is None:
            start = chart_start(end)
        rows = self.provider.candles(symbol=symbol, exchange=exchange,
                                     interval=interval, start=start, end=end,
                                     limit=limit)
        lo, hi = start.timestamp(), end.timestamp()
        rows = [c for c in rows if lo <= c["time"] <= hi]
        # Dhan history ships bars that start after the session close (1m to
        # 15:39, 5m to 15:35 on NSE) while the live pump stops exactly at the
        # close — those ghost bars break the right-edge seam after the
        # historical load. Strip them so history matches the live grid.
        rows = _clamp_to_session(rows, exchange=exchange, interval=interval)
        if limit is not None and len(rows) > limit:
            rows = rows[-limit:]
        return rows

    def ticks(self, *, symbol: str, exchange: str = Exchange.DERIVATIVES,
              interval: str = Timeframe.MIN, start: datetime | None = None,
              end: datetime | None = None, limit: int | None = None) -> list[dict]:
        """Replay ticks for a symbol/range.

        For the ``synthetic`` provider the ticks are synthesized from the
        provider's candles (deterministic, seeded per bar). Every other
        provider serves the *recorded* real ticks written by the live pump
        (JSONL), so replay reflects what was actually traded, not an
        extrapolation.

        The wire format is compact — one entry per bar with ``prices`` /
        ``quantities`` arrays (tick i of a bar is at ``bar.time + i``) — so a
        full contract history fits in a few MB of JSON.

        When the window exceeds the tick budget (``MAX_TICKS``), the FIRST
        bars are kept — replay starts at bar 0, so that is where the intra-bar
        animation is watched. Bars beyond the budget have no ticks and the
        client falls back to plain bars for them.
        """
        if self.name != "synthetic":
            return self._recorded_ticks(symbol, interval, start, end)
        rows = self.candles(symbol=symbol, exchange=exchange, interval=interval,
                            start=start, end=end, limit=limit)
        if not rows:
            return []
        span_s = _INTERVAL_MINUTES.get(interval, 1) * 60  # one tick per second
        max_bars = max(0, MAX_TICKS // span_s)
        if len(rows) > max_bars:
            rows = rows[:max_bars]
        from ntrade.sim.tick_simulator import synthesize_1m_ticks

        out: list[dict] = []
        for r in rows:
            bar_ts = datetime.fromtimestamp(r["time"], tz=timezone.utc)
            seed = int.from_bytes(hashlib.md5(f"{symbol}|{r['time']}".encode()).digest()[:8], "big")
            tks = synthesize_1m_ticks(bar_ts, r["open"], r["high"], r["low"],
                                      r["close"], r["volume"],
                                      seed=seed, seconds=span_s)
            out.append({"time": r["time"],
                        "prices": [float(t.price) for t in tks],
                        "quantities": [int(t.quantity) for t in tks]})
        return out

    def _recorded_ticks(self, symbol: str, interval: str,
                        start: datetime | None, end: datetime | None) -> list[dict]:
        """Group recorded JSONL ticks into the per-bar replay wire format."""
        base = Path(os.environ.get("NTRADE_TICKS_DIR", "data/ticks"))
        span_s = _INTERVAL_MINUTES.get(interval, 1) * 60
        bars: dict[int, dict] = {}
        # Naive start/end are IST wall-clock (the route's contract) — pin them
        # so .timestamp() is the correct epoch regardless of machine tz.
        if start is not None and start.tzinfo is None:
            start = start.replace(tzinfo=_SESSION_TZ)
        if end is not None and end.tzinfo is None:
            end = end.replace(tzinfo=_SESSION_TZ)
        start_ts = start.timestamp() if start else None
        end_ts = end.timestamp() if end else None
        lo_date = (start or datetime.now(tz=_SESSION_TZ)).date()
        hi_date = end.date() if end else lo_date
        d = lo_date
        while d <= hi_date:
            p = base / symbol / f"{d:%Y-%m-%d}.jsonl"
            d += timedelta(days=1)
            if not p.exists():
                continue
            for line in p.read_text().splitlines():
                try:
                    rec = json.loads(line)
                    ts = datetime.fromisoformat(rec["ts"]).timestamp()
                    if start_ts is not None and ts < start_ts:
                        continue
                    if end_ts is not None and ts > end_ts:
                        continue
                    b = int(ts) - (int(ts) % span_s)
                    entry = bars.setdefault(b, {"time": b, "prices": [], "quantities": []})
                    entry["prices"].append(float(rec["price"]))
                    entry["quantities"].append(int(rec["qty"]))
                except Exception:  # noqa: BLE001
                    continue
        return [bars[k] for k in sorted(bars)]

    def quote(self, *, symbol: str, exchange: str = Exchange.DERIVATIVES) -> dict:
        return self.provider.quote(symbol=symbol, exchange=exchange)


def build_service(provider: str | None = None, env: dict | None = None,
                  master: FuturesMaster | None = None) -> MarketDataService:
    """Build a service for ``provider`` (env ``NTRADE_MARKET_PROVIDER``).

    Supported: ``dhan`` (live), ``parquet`` (offline store), ``synthetic``
    (deterministic offline — explicit opt-in only, never a silent default).

    Raises :class:`MarketDataError` when no provider is configured so the
    server can never silently serve fabricated data.
    """
    env = env if env is not None else os.environ
    name = (provider or env.get("NTRADE_MARKET_PROVIDER") or "").strip().lower()
    if not name:
        raise MarketDataError(
            "no market provider configured: set NTRADE_MARKET_PROVIDER or "
            "pass --provider (dhan|parquet|synthetic)"
        )
    master = master or FuturesMaster()
    if name == "dhan":
        service = MarketDataService(DhanProvider(master, env=env), master=master)
    elif name == "parquet":
        base = env.get("NTRADE_DATA_DIR", "data/ohlcv")
        service = MarketDataService(ParquetProvider(master, base_path=base), master=master)
    elif name == "synthetic":
        service = MarketDataService(SyntheticProvider(master), master=master)
    else:
        raise MarketDataError(
            f"unknown market provider {name!r} (use dhan|parquet|synthetic)"
        )
    return service


# ---------------------------------------------------------------------- helpers


def chart_start(now: datetime | None = None, days: int = CHART_DAYS) -> datetime:
    """Midnight IST of the Nth weekday, inclusive of today. Matches UI chartStartIst.

    # ponytail: weekdays only; no holiday calendar — a holiday shrinks the window
    """
    now = now or datetime.now(tz=_SESSION_TZ)
    if now.tzinfo is None:
        now = now.replace(tzinfo=_SESSION_TZ)
    else:
        now = now.astimezone(_SESSION_TZ)
    d = now.date()
    kept = 0
    start = d
    # The backward scan needs enough calendar days to find `days` weekdays
    # (5/7 ratio + weekend slack) — the old fixed 21-day cap silently
    # truncated any window wider than ~15 weekdays. ceil(7*days/5) matches
    # the UI's chartStartIst exactly.
    budget = max(21, (days * 7 + 4) // 5 + 2)
    for _ in range(budget):
        if d.weekday() < 5:
            kept += 1
            start = d
            if kept >= max(1, days):
                break
        d -= timedelta(days=1)
    return datetime.combine(start, time.min, tzinfo=_SESSION_TZ)


def parse_iso(value: str | None, field: str = "timestamp") -> datetime | None:
    """Parse an ISO-8601 timestamp param (naive -> IST, per domain convention)."""
    if value is None or not value.strip():
        return None
    try:
        dt = datetime.fromisoformat(value.strip())
    except ValueError as exc:
        raise ValueError(f"invalid {field}: {value!r} (expected ISO-8601)") from exc
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=_SESSION_TZ)
    return dt


def _f(v) -> float:
    try:
        return float(v or 0.0)
    except (TypeError, ValueError):
        return 0.0


def _int_or_none(v) -> int | None:
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


# Keep `re` import future-proof for symbol validation in routes
_SYMBOL_OK = re.compile(r"^[A-Z0-9 .-]+$")


def is_valid_symbol(symbol: str) -> bool:
    return bool(_SYMBOL_OK.fullmatch(symbol.strip().upper()))
